<a href="https://colab.research.google.com/github/Shivachikkonda02/NLP-Data-Science/blob/main/N-L-P.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import nltk

In [7]:
nltk.download('all')

[nltk_data] Downloading collection 'all'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/abc.zip.
[nltk_data]    | Downloading package alpino to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/alpino.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping
[nltk_data]    |       taggers/averaged_perceptron_tagger_ru.zip.
[nltk_data]    | Downloading package basque_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping grammars/basque_grammars.zip.
[nltk_data]    | Downloading package bcp47 to /root/nltk_data...
[nltk_data]    | Downloading package biocreative_ppi to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   U

True

In [8]:
paragraph="""
Narendra Damodardas Modi (Gujarati: [ˈnəɾendɾə dɑmodəɾˈdɑs ˈmodiː] ⓘ; born 17 September 1950)[b] is an Indian politician who has served as the 14th prime minister of India since May 2014. Modi was the chief minister of Gujarat from 2001 to 2014 and is the Member of Parliament (MP) for Varanasi. He is a member of the Bharatiya Janata Party (BJP) and of the Rashtriya Swayamsevak Sangh (RSS), a right wing Hindu nationalist paramilitary volunteer organisation. He is the longest-serving prime minister from outside the Indian National Congress.
Modi was born and raised in Vadnagar in northeastern Gujarat, where he completed his secondary education. He was introduced to the RSS at the age of eight. His account of helping his father sell tea at the Vadnagar railway station has not been reliably corroborated. At age 18, he was married to Jashodaben Modi, whom he abandoned soon after, only publicly acknowledging her four decades later when legally required to do so. Modi became a full-time worker for the RSS in Gujarat in 1971. The RSS assigned him to the BJP in 1985 and he held several positions within the party hierarchy until 2001, rising to the rank of general secretary.[c]
"""

In [9]:
paragraph

' \nNarendra Damodardas Modi (Gujarati: [ˈnəɾendɾə dɑmodəɾˈdɑs ˈmodiː] ⓘ; born 17 September 1950)[b] is an Indian politician who has served as the 14th prime minister of India since May 2014. Modi was the chief minister of Gujarat from 2001 to 2014 and is the Member of Parliament (MP) for Varanasi. He is a member of the Bharatiya Janata Party (BJP) and of the Rashtriya Swayamsevak Sangh (RSS), a right wing Hindu nationalist paramilitary volunteer organisation. He is the longest-serving prime minister from outside the Indian National Congress.\nModi was born and raised in Vadnagar in northeastern Gujarat, where he completed his secondary education. He was introduced to the RSS at the age of eight. His account of helping his father sell tea at the Vadnagar railway station has not been reliably corroborated. At age 18, he was married to Jashodaben Modi, whom he abandoned soon after, only publicly acknowledging her four decades later when legally required to do so. Modi became a full-time 

In [10]:
## Tokenization -- converts paragraph  to sentences and words.

sentences=nltk.sent_tokenize(paragraph)
sentences

[' \nNarendra Damodardas Modi (Gujarati: [ˈnəɾendɾə dɑmodəɾˈdɑs ˈmodiː] ⓘ; born 17 September 1950)[b] is an Indian politician who has served as the 14th prime minister of India since May 2014.',
 'Modi was the chief minister of Gujarat from 2001 to 2014 and is the Member of Parliament (MP) for Varanasi.',
 'He is a member of the Bharatiya Janata Party (BJP) and of the Rashtriya Swayamsevak Sangh (RSS), a right wing Hindu nationalist paramilitary volunteer organisation.',
 'He is the longest-serving prime minister from outside the Indian National Congress.',
 'Modi was born and raised in Vadnagar in northeastern Gujarat, where he completed his secondary education.',
 'He was introduced to the RSS at the age of eight.',
 'His account of helping his father sell tea at the Vadnagar railway station has not been reliably corroborated.',
 'At age 18, he was married to Jashodaben Modi, whom he abandoned soon after, only publicly acknowledging her four decades later when legally required to do 

In [11]:
for i in sentences:
  print(i)

 
Narendra Damodardas Modi (Gujarati: [ˈnəɾendɾə dɑmodəɾˈdɑs ˈmodiː] ⓘ; born 17 September 1950)[b] is an Indian politician who has served as the 14th prime minister of India since May 2014.
Modi was the chief minister of Gujarat from 2001 to 2014 and is the Member of Parliament (MP) for Varanasi.
He is a member of the Bharatiya Janata Party (BJP) and of the Rashtriya Swayamsevak Sangh (RSS), a right wing Hindu nationalist paramilitary volunteer organisation.
He is the longest-serving prime minister from outside the Indian National Congress.
Modi was born and raised in Vadnagar in northeastern Gujarat, where he completed his secondary education.
He was introduced to the RSS at the age of eight.
His account of helping his father sell tea at the Vadnagar railway station has not been reliably corroborated.
At age 18, he was married to Jashodaben Modi, whom he abandoned soon after, only publicly acknowledging her four decades later when legally required to do so.
Modi became a full-time wor

In [12]:
## Stemmer
from nltk.stem import PorterStemmer

In [13]:
stemmer=PorterStemmer()

In [14]:
stemmer.stem("going")

'go'

In [15]:
## Lemmatization
from nltk.stem import WordNetLemmatizer

In [16]:
lemmatizer=WordNetLemmatizer()

In [17]:
lemmatizer.lemmatize('history')

'history'

In [18]:
len(sentences)

11

In [19]:
## Cleaning the data
import re

In [20]:
corpus=[]
for i in range(len(sentences)):
  review=re.sub('[^a-zA-Z]',' ',sentences[i])
  review=review.lower()
  corpus.append(review)

In [21]:
corpus

['  narendra damodardas modi  gujarati    n  end   d mod   d s  modi      born    september       b  is an indian politician who has served as the   th prime minister of india since may      ',
 'modi was the chief minister of gujarat from      to      and is the member of parliament  mp  for varanasi ',
 'he is a member of the bharatiya janata party  bjp  and of the rashtriya swayamsevak sangh  rss   a right wing hindu nationalist paramilitary volunteer organisation ',
 'he is the longest serving prime minister from outside the indian national congress ',
 'modi was born and raised in vadnagar in northeastern gujarat  where he completed his secondary education ',
 'he was introduced to the rss at the age of eight ',
 'his account of helping his father sell tea at the vadnagar railway station has not been reliably corroborated ',
 'at age     he was married to jashodaben modi  whom he abandoned soon after  only publicly acknowledging her four decades later when legally required to do s

In [22]:
## Stemming
from nltk.corpus import stopwords

for i in corpus:
  words=nltk.word_tokenize(i)
  for word in words:
    if word not in set(stopwords.words('english')):
      print(stemmer.stem(word))

narendra
damodarda
modi
gujarati
n
end
mod
modi
born
septemb
b
indian
politician
serv
th
prime
minist
india
sinc
may
modi
chief
minist
gujarat
member
parliament
mp
varanasi
member
bharatiya
janata
parti
bjp
rashtriya
swayamsevak
sangh
rss
right
wing
hindu
nationalist
paramilitari
volunt
organis
longest
serv
prime
minist
outsid
indian
nation
congress
modi
born
rais
vadnagar
northeastern
gujarat
complet
secondari
educ
introduc
rss
age
eight
account
help
father
sell
tea
vadnagar
railway
station
reliabl
corrobor
age
marri
jashodaben
modi
abandon
soon
publicli
acknowledg
four
decad
later
legal
requir
modi
becam
full
time
worker
rss
gujarat
rss
assign
bjp
held
sever
posit
within
parti
hierarchi
rise
rank
gener
secretari
c


In [23]:
stopwords.words('english')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [24]:
## Lemmatization
for i in corpus:
  words=nltk.word_tokenize(i)
  for word in words:
    if word not in set(stopwords.words('english')):
      print(lemmatizer.lemmatize(word))

narendra
damodardas
modi
gujarati
n
end
mod
modi
born
september
b
indian
politician
served
th
prime
minister
india
since
may
modi
chief
minister
gujarat
member
parliament
mp
varanasi
member
bharatiya
janata
party
bjp
rashtriya
swayamsevak
sangh
r
right
wing
hindu
nationalist
paramilitary
volunteer
organisation
longest
serving
prime
minister
outside
indian
national
congress
modi
born
raised
vadnagar
northeastern
gujarat
completed
secondary
education
introduced
r
age
eight
account
helping
father
sell
tea
vadnagar
railway
station
reliably
corroborated
age
married
jashodaben
modi
abandoned
soon
publicly
acknowledging
four
decade
later
legally
required
modi
became
full
time
worker
r
gujarat
r
assigned
bjp
held
several
position
within
party
hierarchy
rising
rank
general
secretary
c


In [25]:
## Apply Stopwords.Lemmatize
import re
corpus=[]
for i in range(len(sentences)):
  review=re.sub('[^a-zA-Z]',' ',sentences[i])
  review=review.lower()
  review=review.split()
  review=[lemmatizer.lemmatize(word) for word in review if not word in set(stopwords.words('english'))]
  review=' '.join(review)
  corpus.append(review)

In [26]:
## Bag of Words(Index Gets Added To Each Word)
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()

In [27]:
x=cv.fit_transform(corpus)

In [28]:
x

<11x85 sparse matrix of type '<class 'numpy.int64'>'
	with 101 stored elements in Compressed Sparse Row format>

In [29]:
cv.vocabulary_

{'narendra': 43,
 'damodardas': 13,
 'modi': 41,
 'gujarati': 23,
 'end': 17,
 'mod': 40,
 'born': 8,
 'september': 68,
 'indian': 29,
 'politician': 52,
 'served': 69,
 'th': 77,
 'prime': 54,
 'minister': 39,
 'india': 28,
 'since': 72,
 'may': 37,
 'chief': 9,
 'gujarat': 22,
 'member': 38,
 'parliament': 50,
 'mp': 42,
 'varanasi': 80,
 'bharatiya': 6,
 'janata': 31,
 'party': 51,
 'bjp': 7,
 'rashtriya': 59,
 'swayamsevak': 75,
 'sangh': 64,
 'right': 62,
 'wing': 82,
 'hindu': 27,
 'nationalist': 45,
 'paramilitary': 49,
 'volunteer': 81,
 'organisation': 47,
 'longest': 35,
 'serving': 70,
 'outside': 48,
 'national': 44,
 'congress': 11,
 'raised': 57,
 'vadnagar': 79,
 'northeastern': 46,
 'completed': 10,
 'secondary': 65,
 'education': 15,
 'introduced': 30,
 'age': 3,
 'eight': 16,
 'account': 1,
 'helping': 25,
 'father': 18,
 'sell': 67,
 'tea': 76,
 'railway': 56,
 'station': 74,
 'reliably': 60,
 'corroborated': 12,
 'married': 36,
 'jashodaben': 32,
 'abandoned': 0,
 '

In [30]:
## n_grams
cv=CountVectorizer(binary=True,ngram_range=(3,3))
cv.fit_transform(corpus)
cv.vocabulary_

{'narendra damodardas modi': 47,
 'damodardas modi gujarati': 13,
 'modi gujarati end': 46,
 'gujarati end mod': 21,
 'end mod modi': 15,
 'mod modi born': 40,
 'modi born september': 44,
 'born september indian': 10,
 'september indian politician': 68,
 'indian politician served': 28,
 'politician served th': 55,
 'served th prime': 69,
 'th prime minister': 76,
 'prime minister india': 57,
 'minister india since': 38,
 'india since may': 26,
 'modi chief minister': 45,
 'chief minister gujarat': 11,
 'minister gujarat member': 37,
 'gujarat member parliament': 20,
 'member parliament mp': 36,
 'parliament mp varanasi': 52,
 'member bharatiya janata': 35,
 'bharatiya janata party': 6,
 'janata party bjp': 30,
 'party bjp rashtriya': 53,
 'bjp rashtriya swayamsevak': 8,
 'rashtriya swayamsevak sangh': 63,
 'swayamsevak sangh right': 74,
 'sangh right wing': 66,
 'right wing hindu': 64,
 'wing hindu nationalist': 80,
 'hindu nationalist paramilitary': 25,
 'nationalist paramilitary volu

In [31]:
## n_grams
cv=CountVectorizer(binary=True,ngram_range=(2,3))
cv.fit_transform(corpus)
cv.vocabulary_

{'narendra damodardas': 97,
 'damodardas modi': 27,
 'modi gujarati': 94,
 'gujarati end': 44,
 'end mod': 31,
 'mod modi': 83,
 'modi born': 89,
 'born september': 21,
 'september indian': 141,
 'indian politician': 58,
 'politician served': 114,
 'served th': 143,
 'th prime': 158,
 'prime minister': 118,
 'minister india': 79,
 'india since': 54,
 'since may': 149,
 'narendra damodardas modi': 98,
 'damodardas modi gujarati': 28,
 'modi gujarati end': 95,
 'gujarati end mod': 45,
 'end mod modi': 32,
 'mod modi born': 84,
 'modi born september': 91,
 'born september indian': 22,
 'september indian politician': 142,
 'indian politician served': 59,
 'politician served th': 115,
 'served th prime': 144,
 'th prime minister': 159,
 'prime minister india': 119,
 'minister india since': 80,
 'india since may': 55,
 'modi chief': 92,
 'chief minister': 23,
 'minister gujarat': 77,
 'gujarat member': 42,
 'member parliament': 75,
 'parliament mp': 108,
 'mp varanasi': 96,
 'modi chief mini

In [32]:
### TFIDF
from sklearn.feature_extraction.text import TfidfVectorizer
cv=TfidfVectorizer(ngram_range=(1,1),max_features=10)
x=cv.fit_transform(corpus)
cv.vocabulary_

{'modi': 6,
 'born': 1,
 'indian': 3,
 'prime': 8,
 'minister': 5,
 'gujarat': 2,
 'member': 4,
 'party': 7,
 'vadnagar': 9,
 'age': 0}

In [33]:
corpus[0]

'narendra damodardas modi gujarati n end mod modi born september b indian politician served th prime minister india since may'

In [34]:
x[0].toarray()

array([[0.        , 0.41568805, 0.        , 0.41568805, 0.        ,
        0.36557437, 0.58988619, 0.        , 0.41568805, 0.        ]])

In [35]:
!pip install gensim

In [36]:
import gensim

In [37]:
from gensim.models import Word2Vec,keyedvectors

In [38]:
import gensim.downloader as api

wv=api.load("word2vec-google-news-300")
vec_king=wv['king']


[==================================================] 100.0% 1662.8/1662.8MB downloaded


In [39]:
vec_king

array([ 1.25976562e-01,  2.97851562e-02,  8.60595703e-03,  1.39648438e-01,
       -2.56347656e-02, -3.61328125e-02,  1.11816406e-01, -1.98242188e-01,
        5.12695312e-02,  3.63281250e-01, -2.42187500e-01, -3.02734375e-01,
       -1.77734375e-01, -2.49023438e-02, -1.67968750e-01, -1.69921875e-01,
        3.46679688e-02,  5.21850586e-03,  4.63867188e-02,  1.28906250e-01,
        1.36718750e-01,  1.12792969e-01,  5.95703125e-02,  1.36718750e-01,
        1.01074219e-01, -1.76757812e-01, -2.51953125e-01,  5.98144531e-02,
        3.41796875e-01, -3.11279297e-02,  1.04492188e-01,  6.17675781e-02,
        1.24511719e-01,  4.00390625e-01, -3.22265625e-01,  8.39843750e-02,
        3.90625000e-02,  5.85937500e-03,  7.03125000e-02,  1.72851562e-01,
        1.38671875e-01, -2.31445312e-01,  2.83203125e-01,  1.42578125e-01,
        3.41796875e-01, -2.39257812e-02, -1.09863281e-01,  3.32031250e-02,
       -5.46875000e-02,  1.53198242e-02, -1.62109375e-01,  1.58203125e-01,
       -2.59765625e-01,  

In [40]:
wv['man']

array([ 0.32617188,  0.13085938,  0.03466797, -0.08300781,  0.08984375,
       -0.04125977, -0.19824219,  0.00689697,  0.14355469,  0.0019455 ,
        0.02880859, -0.25      , -0.08398438, -0.15136719, -0.10205078,
        0.04077148, -0.09765625,  0.05932617,  0.02978516, -0.10058594,
       -0.13085938,  0.001297  ,  0.02612305, -0.27148438,  0.06396484,
       -0.19140625, -0.078125  ,  0.25976562,  0.375     , -0.04541016,
        0.16210938,  0.13671875, -0.06396484, -0.02062988, -0.09667969,
        0.25390625,  0.24804688, -0.12695312,  0.07177734,  0.3203125 ,
        0.03149414, -0.03857422,  0.21191406, -0.00811768,  0.22265625,
       -0.13476562, -0.07617188,  0.01049805, -0.05175781,  0.03808594,
       -0.13378906,  0.125     ,  0.0559082 , -0.18261719,  0.08154297,
       -0.08447266, -0.07763672, -0.04345703,  0.08105469, -0.01092529,
        0.17480469,  0.30664062, -0.04321289, -0.01416016,  0.09082031,
       -0.00927734, -0.03442383, -0.11523438,  0.12451172, -0.02

In [41]:
wv.most_similar('man')

[('woman', 0.7664012908935547),
 ('boy', 0.6824871301651001),
 ('teenager', 0.6586930155754089),
 ('teenage_girl', 0.6147903203964233),
 ('girl', 0.5921714305877686),
 ('suspected_purse_snatcher', 0.571636438369751),
 ('robber', 0.5585119128227234),
 ('Robbery_suspect', 0.5584409832954407),
 ('teen_ager', 0.5549196600914001),
 ('men', 0.5489763021469116)]

In [42]:
wv.most_similar('king')

[('kings', 0.7138045430183411),
 ('queen', 0.6510956883430481),
 ('monarch', 0.6413194537162781),
 ('crown_prince', 0.6204220056533813),
 ('prince', 0.6159993410110474),
 ('sultan', 0.5864824056625366),
 ('ruler', 0.5797567367553711),
 ('princes', 0.5646552443504333),
 ('Prince_Paras', 0.5432944297790527),
 ('throne', 0.5422105193138123)]

In [43]:
wv.similarity("man",'king')

0.22942673

In [44]:
wv.similarity("html",'programmer')

0.25811526

In [45]:
wv.most_similar('cricket')

[('cricketing', 0.8372225761413574),
 ('cricketers', 0.8165745735168457),
 ('Test_cricket', 0.8094819188117981),
 ('Twenty##_cricket', 0.8068488240242004),
 ('Twenty##', 0.7624265551567078),
 ('Cricket', 0.75413978099823),
 ('cricketer', 0.7372578382492065),
 ('twenty##', 0.7316356897354126),
 ('T##_cricket', 0.7304614186286926),
 ('West_Indies_cricket', 0.6987985968589783)]

In [46]:
wv.most_similar("happy")

[('glad', 0.7408890724182129),
 ('pleased', 0.6632170677185059),
 ('ecstatic', 0.6626912355422974),
 ('overjoyed', 0.6599286794662476),
 ('thrilled', 0.6514049172401428),
 ('satisfied', 0.6437949538230896),
 ('proud', 0.636042058467865),
 ('delighted', 0.627237856388092),
 ('disappointed', 0.6269949674606323),
 ('excited', 0.6247665286064148)]

In [47]:
wv.similarity('cricket','sports')

0.40087253

In [48]:
vec=wv['king']-wv['man']+wv['woman']
vec

array([ 4.29687500e-02, -1.78222656e-01, -1.29089355e-01,  1.15234375e-01,
        2.68554688e-03, -1.02294922e-01,  1.95800781e-01, -1.79504395e-01,
        1.95312500e-02,  4.09919739e-01, -3.68164062e-01, -3.96484375e-01,
       -1.56738281e-01,  1.46484375e-03, -9.30175781e-02, -1.16455078e-01,
       -5.51757812e-02, -1.07574463e-01,  7.91015625e-02,  1.98974609e-01,
        2.38525391e-01,  6.34002686e-02, -2.17285156e-02,  0.00000000e+00,
        4.72412109e-02, -2.17773438e-01, -3.44726562e-01,  6.37207031e-02,
        3.16406250e-01, -1.97631836e-01,  8.59375000e-02, -8.11767578e-02,
       -3.71093750e-02,  3.15551758e-01, -3.41796875e-01, -4.68750000e-02,
        9.76562500e-02,  8.39843750e-02, -9.71679688e-02,  5.17578125e-02,
       -5.00488281e-02, -2.20947266e-01,  2.29492188e-01,  1.26403809e-01,
        2.49023438e-01,  2.09960938e-02, -1.09863281e-01,  5.81054688e-02,
       -3.35693359e-02,  1.29577637e-01,  2.41699219e-02,  3.48129272e-02,
       -2.60009766e-01,  

In [49]:
wv.most_similar([vec])

[('king', 0.8449392318725586),
 ('queen', 0.7300517559051514),
 ('monarch', 0.645466148853302),
 ('princess', 0.6156251430511475),
 ('crown_prince', 0.5818676352500916),
 ('prince', 0.5777117609977722),
 ('kings', 0.5613663792610168),
 ('sultan', 0.5376775860786438),
 ('Queen_Consort', 0.5344247817993164),
 ('queens', 0.5289887189865112)]

In [50]:
# Word Embedding Techniques Using Embedding Layer in Keras

In [51]:
from tensorflow.keras.preprocessing.text import one_hot

In [52]:
### sentences
sent=['the glass of milk',
      'the glass of juice',
      'the cup of tea',
      'I am a good boy',
      'I am a good developer',
      'understand the meaning of words',
      'your videos are good']

In [53]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [54]:
## Vacabulary size
voc_size=10000

In [55]:
# One HOt Representation
onehot_repr=[one_hot(words,voc_size) for words in sent]
print(onehot_repr)

[[1835, 1058, 1284, 7641], [1835, 1058, 1284, 8665], [1835, 1292, 1284, 5002], [2713, 819, 1343, 5509, 1434], [2713, 819, 1343, 5509, 3101], [3401, 1835, 1147, 1284, 4661], [4873, 3302, 7871, 5509]]


In [56]:
## Word Wmbedding Representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [57]:
import numpy as np

In [58]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 1835 1058 1284 7641]
 [   0    0    0    0 1835 1058 1284 8665]
 [   0    0    0    0 1835 1292 1284 5002]
 [   0    0    0 2713  819 1343 5509 1434]
 [   0    0    0 2713  819 1343 5509 3101]
 [   0    0    0 3401 1835 1147 1284 4661]
 [   0    0    0    0 4873 3302 7871 5509]]


In [59]:
dim=10

In [60]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [61]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [64]:
print(model.predict)

<bound method Model.predict of <keras.src.engine.sequential.Sequential object at 0x7b6ef99a64d0>>


In [65]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 58ms/step
[[[ 0.04535898 -0.01822537  0.0372637   0.00650791 -0.02279758
   -0.0006565  -0.02315592  0.03377397 -0.03998673 -0.04670268]
  [ 0.04535898 -0.01822537  0.0372637   0.00650791 -0.02279758
   -0.0006565  -0.02315592  0.03377397 -0.03998673 -0.04670268]
  [ 0.04535898 -0.01822537  0.0372637   0.00650791 -0.02279758
   -0.0006565  -0.02315592  0.03377397 -0.03998673 -0.04670268]
  [ 0.04535898 -0.01822537  0.0372637   0.00650791 -0.02279758
   -0.0006565  -0.02315592  0.03377397 -0.03998673 -0.04670268]
  [-0.02983399 -0.04671434  0.02431984 -0.03019094 -0.0186194
    0.03550741 -0.02152254  0.02449501  0.02719286 -0.0290622 ]
  [-0.01951648 -0.009033   -0.00285492  0.02961854  0.0384522
    0.00230422 -0.04558057 -0.014224   -0.03924211  0.01744713]
  [-0.0279919   0.00421857  0.02304429  0.00516342  0.02114821
    0.04406894 -0.04212383  0.01704884 -0.00879437 -0.03326557]
  [-0.0199929  -0.0440145   0.00735828 -0.01229183  0.0285852