<a href="https://colab.research.google.com/github/Shivachikkonda02/NLP-Data-Science/blob/main/NLP%20Data%20Science%20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import nltk

In [2]:
sentence='Our nation faces a profound climate crisis that is impacting every American '

In [3]:
sentence

'Our nation faces a profound climate crisis that is impacting every American '

In [4]:
#Check Whether the word 'nation' belongs to that text using the following code?
def find_word(word,sentence):
  return word in sentence

In [5]:
find_word('nation',sentence)

True

In [6]:
#Find out the index value of the word 'crisis' using the following code?
def get_index(word,text):
  return text.index(word)

In [7]:
get_index('crisis',sentence)

36

In [8]:
# To find out the rank of the wprd 'American' use the following code

get_index('American',sentence.split())

11

In [9]:
# To print the third word of the given text ,use the following code

def get_word(text,rank):
  return text.split()[rank]

In [10]:
get_word(sentence,2)

'faces'

In [20]:
nltk.download('all')

[nltk_data] Downloading collection 'all'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/abc.zip.
[nltk_data]    | Downloading package alpino to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/alpino.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping
[nltk_data]    |       taggers/averaged_perceptron_tagger_ru.zip.
[nltk_data]    | Downloading package basque_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping grammars/basque_grammars.zip.
[nltk_data]    | Downloading package bcp47 to /root/nltk_data...
[nltk_data]    | Downloading package biocreative_ppi to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   U

True

In [21]:
# Tokenization

text="This is an example sentence. It has multiple words"

In [22]:
from nltk.tokenize import word_tokenize , sent_tokenize

In [23]:
# Word Tokenization

tokens=word_tokenize(text)

In [24]:
tokens

['This',
 'is',
 'an',
 'example',
 'sentence',
 '.',
 'It',
 'has',
 'multiple',
 'words']

In [25]:
# Sentence Tokenization

sentences=sent_tokenize(text)

In [26]:
sentences

['This is an example sentence.', 'It has multiple words']

In [27]:
for sentence in sentences:
  print(sentence)

This is an example sentence.
It has multiple words


In [28]:
# POs Tagging

text=' The quick brown fox jumps over the lazy dog.'

In [32]:
# Tokenization
tokens=word_tokenize(text)

# PoS Tagging
pos_tags=nltk.pos_tag(tokens)
print('POS Tags',pos_tags)

POS Tags [('The', 'DT'), ('quick', 'JJ'), ('brown', 'NN'), ('fox', 'NN'), ('jumps', 'VBZ'), ('over', 'IN'), ('the', 'DT'), ('lazy', 'JJ'), ('dog', 'NN'), ('.', '.')]


In [35]:
for pos_tag in pos_tags:
  print(pos_tag)

('The', 'DT')
('quick', 'JJ')
('brown', 'NN')
('fox', 'NN')
('jumps', 'VBZ')
('over', 'IN')
('the', 'DT')
('lazy', 'JJ')
('dog', 'NN')
('.', '.')


In [37]:
# Stopword Removal


from nltk.corpus import stopwords

In [65]:
text='Artificial intelligence (AI) is rapidly transforming many aspects of our lives. From facial recognition software to recommendation algorithms, AI is having a profound impact on society. However, ethical considerations surrounding AI development and deployment need careful attention.'

In [66]:
# Tokenization
tokens = nltk.word_tokenize(text)

# Stop Word List (customizable)
stop_words = set(stopwords.words('english'))  # Get English stop words

# Remove stop words (Option 1: Complete Removal)
filtered_tokens = [token for token in tokens if token not in stop_words]
print("Original Sentence:", text)
print("Stop Words Removed (Option 1):", filtered_tokens)


Original Sentence: Artificial intelligence (AI) is rapidly transforming many aspects of our lives. From facial recognition software to recommendation algorithms, AI is having a profound impact on society. However, ethical considerations surrounding AI development and deployment need careful attention.
Stop Words Removed (Option 1): ['Artificial', 'intelligence', '(', 'AI', ')', 'rapidly', 'transforming', 'many', 'aspects', 'lives', '.', 'From', 'facial', 'recognition', 'software', 'recommendation', 'algorithms', ',', 'AI', 'profound', 'impact', 'society', '.', 'However', ',', 'ethical', 'considerations', 'surrounding', 'AI', 'development', 'deployment', 'need', 'careful', 'attention', '.']


In [68]:
# Text normalization

text="I Visited the US from the UK on 22-10-18"

normalized_text=text.lower()
normalized_text

'i visited the us from the uk on 22-10-18'

In [69]:
# Replacing
normalized_text=text.replace('UK','United Kingdom')
normalized_text

'I Visited the US from the United Kingdom on 22-10-18'

In [70]:
# Upper Case
normalized_text=text.upper()
normalized_text

'I VISITED THE US FROM THE UK ON 22-10-18'

In [71]:
# Spelling Correction

import textblob

In [72]:
from textblob import TextBlob

In [83]:
# Text with misspelling
text='Ths sentance has a misspelling.'

In [84]:
# Correct the spelling using TextBlob's spellcheck method
corrected_text=TextBlob(text).correct()

# Print the original and corrected text
print("Original Text:", text)
print("Corrected Text:", corrected_text)


Original Text: Ths sentance has a misspelling.
Corrected Text: The sentence has a misspelling.


In [85]:
# Stemming
# Porter Stemmer

from nltk.stem import PorterStemmer

In [119]:
words=['eating','eats','eaten','writing','writes','programming','programs','history']

In [120]:
stemmer=PorterStemmer()

In [121]:
for word in words:
  print(word,"-->",stemmer.stem(word))

eating --> eat
eats --> eat
eaten --> eaten
writing --> write
writes --> write
programming --> program
programs --> program
history --> histori


In [122]:
# Snowball Stemmer

from nltk.stem import SnowballStemmer

In [123]:
snow_stem=SnowballStemmer('english')

In [124]:
for word in words:
  print(word,"-->",snow_stem.stem(word))

eating --> eat
eats --> eat
eaten --> eaten
writing --> write
writes --> write
programming --> program
programs --> program
history --> histori


In [125]:
# Lemmatization

from nltk.stem import WordNetLemmatizer

In [126]:
lemmatizer=WordNetLemmatizer()

In [127]:
for word in words:
  print(word,'-->',lemmatizer.lemmatize(word))

eating --> eating
eats --> eats
eaten --> eaten
writing --> writing
writes --> writes
programming --> programming
programs --> program
history --> history


In [128]:
# stopwords Removal with Lemmatizatiom

corpus="""The Natural Language Toolkit (NLTK) is a powerful library for natural language processing (NLP) tasks in Python.
It provides tools for tokenization, stopword removal, stemming, lemmatization, part-of-speech tagging, and more.
 In Google Colab, you can easily install NLTK and download necessary resources to unlock its potential for your NLP projects."""


In [130]:
data=nltk.sent_tokenize(corpus)

In [131]:
data

['The Natural Language Toolkit (NLTK) is a powerful library for natural language processing (NLP) tasks in Python.',
 'It provides tools for tokenization, stopword removal, stemming, lemmatization, part-of-speech tagging, and more.',
 'In Google Colab, you can easily install NLTK and download necessary resources to unlock its potential for your NLP projects.']

In [134]:
for i in range (len(data)):
  words=nltk.word_tokenize(data[i])
  words=[lemmatizer.lemmatize(word) for word in words if word not in set (stopwords.words('english'))]
  data[i]=' '.join(words)

In [135]:
data

['natur languag toolkit ( nltk ) power librari natur languag process ( nlp ) task python .',
 'provid tool token , stopword remov , stem , lemmat , part-of-speech tag , .',
 'googl colab , easili instal nltk download necessari resourc unlock potenti nlp project .']

In [138]:
# Named Entity Recognition
import spacy

nlp=spacy.load("en_core_web_sm")


In [139]:
nlp.pipe_names

['tok2vec', 'tagger', 'parser', 'attribute_ruler', 'lemmatizer', 'ner']

In [149]:
doc=nlp("Tesla Inc is going to acquire Twitter Inc for $45 bilion")

for ent in doc.ents:
  print(ent.text,"|",ent.label_,"|",spacy.explain(ent.label_))

Tesla Inc | ORG | Companies, agencies, institutions, etc.
Twitter Inc | ORG | Companies, agencies, institutions, etc.
45 | MONEY | Monetary values, including unit


In [150]:
from spacy import displacy
displacy.render(doc,style='ent')

In [151]:
nlp.pipe_labels['ner']

['CARDINAL',
 'DATE',
 'EVENT',
 'FAC',
 'GPE',
 'LANGUAGE',
 'LAW',
 'LOC',
 'MONEY',
 'NORP',
 'ORDINAL',
 'ORG',
 'PERCENT',
 'PERSON',
 'PRODUCT',
 'QUANTITY',
 'TIME',
 'WORK_OF_ART']

In [153]:
doc=nlp('Michael Bloomberg founded Bloomberg in 1982')

In [156]:
for ent in doc.ents:
  print(ent.text,"|",ent.label_,"|",spacy.explain(ent.label_))

Michael Bloomberg | PERSON | People, including fictional
Bloomberg | PERSON | People, including fictional
1982 | DATE | Absolute or relative dates or periods


In [160]:
from spacy import displacy
displacy.render(doc,style='ent')

In [161]:
type(doc[0])

spacy.tokens.token.Token

In [162]:
doc[2:5]

founded Bloomberg in

In [164]:
type(doc[2:5])

spacy.tokens.span.Span

In [166]:
# Text Representation

import pandas as pd
import numpy as np

In [167]:
df=pd.read_csv("/content/spam.csv")
df

Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [168]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [170]:
df['spam']=df['Category'].apply(lambda x:1 if x=='spam' else 0)

In [171]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [172]:
df['spam'].value_counts()

spam
0    4825
1     747
Name: count, dtype: int64

In [174]:
from sklearn.model_selection import train_test_split

In [222]:
x_train,x_test,y_train,y_test=train_test_split(df.Message,df.spam,test_size=0.2,random_state=0)

In [176]:
x_train.shape

(4457,)

In [177]:
x_test.shape

(1115,)

In [178]:
type(x_train)

pandas.core.series.Series

In [179]:
x_train[:4]

1114    No I'm good for the movie, is it ok if I leave...
3589    If you were/are free i can give. Otherwise nal...
3095    Have you emigrated or something? Ok maybe 5.30...
1012          I just got home babe, are you still awake ?
Name: Message, dtype: object

In [180]:
y_train[:4]

1114    0
3589    0
3095    0
1012    0
Name: spam, dtype: int64

In [181]:
x_train.values

array(["No I'm good for the movie, is it ok if I leave in an hourish?",
       'If you were/are free i can give. Otherwise nalla adi entey nattil kittum',
       'Have you emigrated or something? Ok maybe 5.30 was a bit hopeful...',
       ...,
       "For ur chance to win a £250 cash every wk TXT: ACTION to 80608. T's&C's www.movietrivia.tv custcare 08712405022, 1x150p/wk",
       'R U &SAM P IN EACHOTHER. IF WE MEET WE CAN GO 2 MY HOUSE',
       'Mm feeling sleepy. today itself i shall get that dear'],
      dtype=object)

In [184]:
from sklearn.feature_extraction.text import CountVectorizer



In [185]:
v=CountVectorizer()

In [186]:
x_train_cv=v.fit_transform(x_train.values)
x_train_cv

<4457x7788 sparse matrix of type '<class 'numpy.int64'>'
	with 59003 stored elements in Compressed Sparse Row format>

In [204]:
x_train_cv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [190]:
x_train_cv.shape

(4457, 7788)

In [192]:
v.get_feature_names_out()[6847]

'thandiyachu'

In [193]:
v.vocabulary_

{'no': 4809,
 'good': 3196,
 'for': 2943,
 'the': 6861,
 'movie': 4623,
 'is': 3769,
 'it': 3781,
 'ok': 4932,
 'if': 3615,
 'leave': 4084,
 'in': 3661,
 'an': 957,
 'hourish': 3529,
 'you': 7751,
 'were': 7502,
 'are': 1048,
 'free': 2990,
 'can': 1625,
 'give': 3158,
 'otherwise': 5021,
 'nalla': 4696,
 'adi': 816,
 'entey': 2603,
 'nattil': 4716,
 'kittum': 3977,
 'have': 3369,
 'emigrated': 2570,
 'or': 4993,
 'something': 6351,
 'maybe': 4423,
 '30': 432,
 'was': 7429,
 'bit': 1359,
 'hopeful': 3505,
 'just': 3899,
 'got': 3213,
 'home': 3485,
 'babe': 1191,
 'still': 6524,
 'awake': 1169,
 'kay': 3926,
 'since': 6213,
 'we': 7455,
 'out': 5028,
 'already': 924,
 'me': 4428,
 'not': 4845,
 'workin': 7637,
 'once': 4954,
 'get': 3132,
 'job': 3852,
 'what': 7515,
 'he': 3379,
 'said': 5915,
 'matter': 4412,
 'my': 4679,
 'mind': 4505,
 'saying': 5963,
 'some': 6341,
 'other': 5019,
 'there': 6880,
 'oh': 4927,
 'yeah': 7723,
 'and': 961,
 'diet': 2305,
 'flew': 2891,
 'window': 756

In [205]:
x_train_np=x_train_cv.toarray()

In [196]:
x_train_np[:4]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [206]:
np.where(x_train_np[0]!=0)

(array([ 957, 2943, 3196, 3529, 3615, 3661, 3769, 3781, 4084, 4623, 4809,
        4932, 6861]),)

In [200]:
x_train_np[0][2943]

1

In [202]:
from sklearn.naive_bayes import MultinomialNB

In [203]:
model=MultinomialNB()
model.fit(x_train_cv,y_train)

MultinomialNB()

In [207]:
x_test_cv=v.transform(x_test)

In [208]:
from sklearn.metrics import classification_report

In [211]:
y_pred=model.predict(x_test_cv)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       955
           1       0.98      0.93      0.95       160

    accuracy                           0.99      1115
   macro avg       0.98      0.96      0.97      1115
weighted avg       0.99      0.99      0.99      1115



In [224]:
# Text Representation using bag of n-grams
from sklearn.feature_extraction.text import CountVectorizer

In [227]:
v=CountVectorizer(ngram_range=(1,3))
v.fit(['Thor Hathodwala is looking for a job'])
v.vocabulary_

{'thor': 12,
 'hathodwala': 2,
 'is': 5,
 'looking': 9,
 'for': 0,
 'job': 8,
 'thor hathodwala': 13,
 'hathodwala is': 3,
 'is looking': 6,
 'looking for': 10,
 'for job': 1,
 'thor hathodwala is': 14,
 'hathodwala is looking': 4,
 'is looking for': 7,
 'looking for job': 11}

In [230]:
# Word Vectors
import spacy

In [231]:
!python -m spacy download en_core_web_lg

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 587.7/587.7 MB 2.4 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_lg')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.


In [233]:
nlp=spacy.load('en_core_web_lg')

In [235]:
doc=nlp('dog cat bannana kem')

for token in doc:
  print(token.text,"vector", token.has_vector,"OOv:",token.is_oov)

dog vector True OOv: False
cat vector True OOv: False
bannana vector False OOv: True
kem vector False OOv: True


In [236]:
doc[0].vector.shape

(300,)

In [237]:
base_token=nlp('bread')

In [238]:
base_token.vector.shape

(300,)

In [239]:
doc=nlp("sandwich burger car tiger human wheat")

for token in doc:
  print(f"{token.text}<->{base_token.text:}",token.similarity(base_token))

sandwich<->bread 0.6341067010130894
burger<->bread 0.47520687769584247
car<->bread 0.06451533308853552
tiger<->bread 0.04764611675903374
human<->bread 0.2151154210812192
wheat<->bread 0.6150360888607199


In [242]:
def print_similarity(base_word,words_to_compare):
  base_token=nlp(base_word)
  doc=nlp(words_to_compare)
  for token in doc:
    print(f"{token.text} <-> {base_token.text}: ",token.similarity(base_token))

In [243]:
print_similarity('iphone','apple samsung dog kitchen')

apple <-> iphone:  0.4387907401919904
samsung <-> iphone:  0.670859081425417
dog <-> iphone:  0.08211864228011527
kitchen <-> iphone:  0.20595275957182724


In [245]:
king=nlp.vocab['king'].vector
man=nlp.vocab['man'].vector
woman=nlp.vocab['woman'].vector
queen=nlp.vocab['queen'].vector

result=king-man+woman

In [247]:
from sklearn.metrics.pairwise import cosine_similarity

cosine_similarity([result],[queen])

array([[0.61780137]], dtype=float32)

In [248]:
# Word Vectors in Gensim
import gensim.downloader as api

In [249]:
wv=api.load("word2vec-google-news-300")

[==================================================] 100.0% 1662.8/1662.8MB downloaded


In [251]:
wv.similarity(w1='great',w2='well')

0.4098271

In [252]:
wv.similarity(w1='profit',w2='well')

0.048574597

In [254]:
wv.most_similar('good')

[('great', 0.7291510105133057),
 ('bad', 0.7190051078796387),
 ('terrific', 0.6889115571975708),
 ('decent', 0.6837348341941833),
 ('nice', 0.6836092472076416),
 ('excellent', 0.644292950630188),
 ('fantastic', 0.6407778263092041),
 ('better', 0.6120728850364685),
 ('solid', 0.5806034803390503),
 ('lousy', 0.576420247554779)]

In [258]:
wv.doesnt_match(['dog','cat','lion','microsoft'])

'microsoft'