<a href="https://colab.research.google.com/github/Shivachikkonda02/NLP-Data-Science/blob/main/Word_Embedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
from tensorflow.keras.preprocessing.text import one_hot

In [4]:
## Sentences
sent=[
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good'
]

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
## Vocabulary size
voc_size=10000

In [7]:
## One Hot Representation

one_hot_rep=[one_hot(words,voc_size)for words in sent]
print(one_hot_rep) ## it gives the the position number of 1.

[[1684, 7330, 7947, 8800], [1684, 7330, 7947, 7797], [1684, 5741, 7947, 6933], [7072, 6129, 2038, 5644, 6762], [7072, 6129, 2038, 5644, 9136], [4407, 1684, 207, 7947, 784], [1540, 2843, 8959, 5644]]


In [10]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np


In [11]:
sent_length=8
embedded_docs=pad_sequences(one_hot_rep,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 1684 7330 7947 8800]
 [   0    0    0    0 1684 7330 7947 7797]
 [   0    0    0    0 1684 5741 7947 6933]
 [   0    0    0 7072 6129 2038 5644 6762]
 [   0    0    0 7072 6129 2038 5644 9136]
 [   0    0    0 4407 1684  207 7947  784]
 [   0    0    0    0 1540 2843 8959 5644]]


In [13]:
dim=10
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [14]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [15]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 207ms/step
[[[ 0.03536971  0.01588785  0.04343149  0.00223995 -0.0010362
   -0.00010109 -0.01037843  0.02536288  0.03378666  0.01308124]
  [ 0.03536971  0.01588785  0.04343149  0.00223995 -0.0010362
   -0.00010109 -0.01037843  0.02536288  0.03378666  0.01308124]
  [ 0.03536971  0.01588785  0.04343149  0.00223995 -0.0010362
   -0.00010109 -0.01037843  0.02536288  0.03378666  0.01308124]
  [ 0.03536971  0.01588785  0.04343149  0.00223995 -0.0010362
   -0.00010109 -0.01037843  0.02536288  0.03378666  0.01308124]
  [-0.00164528  0.01117595 -0.00764568  0.00604576 -0.00925063
    0.00739163 -0.03427223  0.01137732 -0.00923347  0.00955385]
  [ 0.00424408 -0.03906052  0.04475557  0.00679027 -0.03118187
    0.02330676  0.01543561 -0.03283137 -0.04082644  0.02319032]
  [ 0.00511192  0.02291157  0.00533636  0.01257377 -0.03262553
   -0.01664948 -0.00656624  0.0329698  -0.01662129  0.04568905]
  [-0.03756328  0.03795953 -0.03526846 -0.03633614 -0.04125885

In [16]:
embedded_docs[0]

array([   0,    0,    0,    0, 1684, 7330, 7947, 8800], dtype=int32)